module.exports = [
    {
        home: "SRH",
        away: "RCB",
        fixture: "5/4,8"
    }, {
        home: "RPS",
        away: "MI",
        fixture: "6/4,8"
    }, {
        home: "GL",
        away: "KKR",
        fixture: "7/4,8"
    }, {
        home: "KXIP",
        away: "RPS",
        fixture: "8/4,4"
    }, {
        home: "RCB",
        away: "DD",
        fixture: "8/4,8"
    }, {
        home: "SRH",
        away: "GL",
        fixture: "9/4,4"
    }, {
        home: "MI",
        away: "KKR",
        fixture: "9/4,8"
    }, {
        home: "KXIP",
        away: "RCB",
        fixture: "10/4,8"
    }, {
        home: "RPS",
        away: "DD",
        fixture: "11/4,8"
    }, {
        home: "MI",
        away: "SRH",
        fixture: "12/4,8"
    }, {
        home: "KKR",
        away: "KXIP",
        fixture: "13/4,8"
    }, {
        home: "RCB",
        away: "MI",
        fixture: "14/4,4"
    }, {
        home: "GL",
        away: "RPS",
        fixture: "14/4,8"
    }, {
        home: "KKR",
        away: "SRH",
        fixture: "15/4,4"
    }, {
        home: "DD",
        away: "KXIP",
        fixture: "15/4,8"
    }, {
        home: "MI",
        away: "GL",
        fixture: "16/4,4"
    }, {
        home: "RCB",
        away: "RPS",
        fixture: "16/4,8"
    }, {
        home: "DD",
        away: "KKR",
        fixture: "17/4,4"
    }, {
        home: "SRH",
        away: "KXIP",
        fixture: "17/4,8"
    }, {
        home: "GL",
        away: "RCB",
        fixture: "18/4,8"
    }, {
        home: "SRH",
        away: "DD",
        fixture: "19/4,8"
    }, {
        home: "KXIP",
        away: "MI",
        fixture: "20/4,8"
    }, {
        home: "KKR",
        away: "GL",
        fixture: "21/4,8"
    }, {
        home: "DD",
        away: "MI",
        fixture: "22/4,4"
    }, {
        home: "RPS",
        away: "SRH",
        fixture: "22/4,8"
    }, {
        home: "GL",
        away: "KXIP",
        fixture: "23/4,4"
    }, {
        home: "KKR",
        away: "RCB",
        fixture: "23/4,8"
    }, {
        home: "MI",
        away: "RPS",
        fixture: "24/4,8"
    }, {
        home: "RCB",
        away: "SRH",
        fixture: "25/4,8"
    }, {
        home: "RPS",
        away: "KKR",
        fixture: "26/4,8"
    }, {
        home: "RCB",
        away: "GL",
        fixture: "27/4,8"
    }, {
        home: "KKR",
        away: "DD",
        fixture: "28/4,4"
    }, {
        home: "KXIP",
        away: "SRH",
        fixture: "28/4,8"
    }, {
        home: "RPS",
        away: "RCB",
        fixture: "29/4,4"
    }, {
        home: "GL",
        away: "MI",
        fixture: "29/4,8"
    }, {
        home: "KXIP",
        away: "DD",
        fixture: "30/4,4"
    }, {
        home: "SRH",
        away: "KKR",
        fixture: "30/4,8"
    }, {
        home: "MI",
        away: "RCB",
        fixture: "1/5,4"
    }, {
        home: "RPS",
        away: "GL",
        fixture: "1/5,8"
    }, {
        home: "DD",
        away: "SRH",
        fixture: "2/5,8"
    }, {
        home: "KKR",
        away: "RPS",
        fixture: "3/5,8"
    }, {
        home: "DD",
        away: "GL",
        fixture: "4/5,8"
    }, {
        home: "RCB",
        away: "KXIP",
        fixture: "5/5,8"
    }, {
        home: "SRH",
        away: "RPS",
        fixture: "6/5,4"
    }, {
        home: "MI",
        away: "DD",
        fixture: "6/5,8"
    }, {
        home: "RCB",
        away: "KKR",
        fixture: "7/5,4"
    }, {
        home: "KXIP",
        away: "GL",
        fixture: "7/5,8"
    }, {
        home: "SRH",
        away: "MI",
        fixture: "8/5,8"
    }, {
        home: "KXIP",
        away: "KKR",
        fixture: "9/5,8"
    }, {
        home: "GL",
        away: "DD",
        fixture: "10/5,8"
    }, {
        home: "MI",
        away: "KXIP",
        fixture: "11/5,8"
    }, {
        home: "DD",
        away: "RPS",
        fixture: "12/5,8"
    }, {
        home: "GL",
        away: "SRH",
        fixture: "13/5,4"
    }, {
        home: "KKR",
        away: "MI",
        fixture: "13/5,8"
    }, {
        home: "RPS",
        away: "KXIP",
        fixture: "14/5,4"
    }, {
        home: "DD",
        away: "RCB",
        fixture: "14/5,8"
    }
];